"""
model/core/logistic.py — Build the P×N deferral probability matrix D.

D[p, n] = P(provider declines | client p offered facility n)

Pipeline:
  1. build_client_snapshot()  — one row per unique patient (most recent priority)
  2. recover_facility_effects() — estimate u_n per facility from historical offers
  3. build_gender_map()       — facility-level gender limitation from vacancy data
  4. build_D_matrix()         — full P×N matrix + gender block list
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from datetime import date

from model.parameters import (
    compute_r_p,
    compute_p_pn,
    encode_priority,
    is_gender_mismatch,
    is_flu_season,
    funding_to_h_n,
    ALPHA, BETA,
)


# ---------------------------------------------------------------------------
# 1.  Client snapshot
# ---------------------------------------------------------------------------

def build_client_snapshot(entries_df: pd.DataFrame) -> pd.DataFrame:
    """
    One row per unique patient — use the most recent offer row
    (highest DateClientOffered) to get the most up-to-date priority and scores.

    Columns returned (all needed to compute p_pn):
        PatientID, ClientGender, WaitlistPriority, CPS_Score, ADL_SP_Hierarchy,
        _r_p  (pre-computed composite complexity)
    """
    snapshot = (
        entries_df
        .sort_values("DateClientOffered", ascending=False)
        .drop_duplicates(subset="PatientID", keep="first")
        .reset_index(drop=True)
    )
    # Recompute r_p cleanly (don't rely on stored _r_p)
    snapshot = snapshot.copy()
    snapshot["r_p"] = snapshot.apply(
        lambda r: compute_r_p(r["CPS_Score"], r["ADL_SP_Hierarchy"]), axis=1
    )
    snapshot["q_p"] = snapshot["WaitlistPriority"].map(encode_priority)

    return snapshot[[
        "PatientID", "ClientGender", "WaitlistPriority",
        "CPS_Score", "ADL_SP_Hierarchy", "r_p", "q_p",
    ]].copy()


# ---------------------------------------------------------------------------
# 2.  Facility random effects  u_n
# ---------------------------------------------------------------------------

def recover_facility_effects(
    entries_df: pd.DataFrame,
    facilities_df: pd.DataFrame,
) -> dict[str, float]:
    """
    Estimate u_n for each facility by back-solving from stored _p_pn values.

        logit(p_pn) = α + u_n + Σ β_i x_i
        u_n = logit(p_pn) − (α + Σ β_i x_i)

    For facilities with no historical offers, u_n defaults to 0.0 (prior mean).

    Returns
    -------
    dict {ProviderName: u_n_estimate}
    """
    df = entries_df.copy()

    # Compute deterministic part (u_n = 0)
    df["q_p"] = df["WaitlistPriority"].map(encode_priority)
    df["r_p"] = df.apply(
        lambda r: compute_r_p(r["CPS_Score"], r["ADL_SP_Hierarchy"]), axis=1
    )
    # h_n from stored _h_n column (generated by mock_data.py)
    # g_pn from stored _g_pn column

    def _logit_det(row) -> float:
        z = (
            ALPHA
            + BETA["r_p"]        * row["r_p"]
            + BETA["q_p"]        * row["q_p"]
            + BETA["h_n"]        * row["_h_n"]
            + BETA["r_p_x_h_n"]  * row["r_p"] * row["_h_n"]
            + BETA["g_pn"]       * row["_g_pn"]
            + BETA["t"]          * (is_flu_season(row["DateClientOffered"])
                                    if row["DateClientOffered"] else 0)
        )
        return z  # logit of deterministic part

    df["z_det"] = df.apply(_logit_det, axis=1)
    p_stored = df["_p_pn"].clip(1e-9, 1 - 1e-9)
    df["logit_stored"] = np.log(p_stored / (1 - p_stored))
    df["u_n_est"] = df["logit_stored"] - df["z_det"]

    # Average per facility
    u_n_map = df.groupby("ProviderName")["u_n_est"].mean().to_dict()

    # Fill missing facilities with 0
    for name in facilities_df["ProviderName"]:
        if name not in u_n_map:
            u_n_map[name] = 0.0

    return u_n_map


# ---------------------------------------------------------------------------
# 3.  Facility-level gender limitation
# ---------------------------------------------------------------------------

def build_gender_map(vacancies_df: pd.DataFrame) -> dict[str, str | None]:
    """
    Compute facility-level gender limitation from vacancy data.

    Rule: a facility is gender-restricted (e.g. Female-only) only if > 60%
    of its TOTAL vacancies carry that specific limitation.
    The denominator is all vacancies at the facility, not just limited ones.
    This prevents a facility with 2 Female-limited rooms out of 27 total
    from being incorrectly flagged as Female-only.

    In practice, with ~10% of vacancies gender-limited, essentially no
    facility will trigger this threshold — which is correct: almost every
    facility has plenty of unrestricted rooms available.

    The gender constraint is most meaningful at the vacancy level (DES, Step 5).
    At the facility level (LP, Step 3) it only fires if a facility is
    overwhelmingly single-gender restricted.

    Returns
    -------
    dict {ProviderName: "Female" | "Male" | None}
    """
    result: dict[str, str | None] = {}
    for provider, grp in vacancies_df.groupby("ProviderName"):
        total = len(grp)
        facility_lim = None
        for gender in ("Female", "Male"):
            frac = (grp["RoomGenderLimitation"] == gender).sum() / total
            if frac > 0.60:
                facility_lim = gender
                break
        result[provider] = facility_lim
    return result


# ---------------------------------------------------------------------------
# 4.  D matrix
# ---------------------------------------------------------------------------

def build_D_matrix(
    snapshot: pd.DataFrame,
    facilities_df: pd.DataFrame,
    u_n_map: dict[str, float],
    gender_map: dict[str, str | None],
    offer_date: date | None = None,
) -> tuple[np.ndarray, list[tuple[int, int]]]:
    """
    Build the P×N deferral probability matrix and identify gender-blocked pairs.

    Parameters
    ----------
    snapshot      : client snapshot from build_client_snapshot()
    facilities_df : facility_details DataFrame
    u_n_map       : facility random effects from recover_facility_effects()
    gender_map    : facility-level gender limitations from build_gender_map()
    offer_date    : reference date for flu-season flag (default: today)

    Returns
    -------
    D             : np.ndarray shape (P, N), values in (0, 1)
    gender_blocks : list of (p_idx, n_idx) pairs where x_pn must be 0
    """
    if offer_date is None:
        offer_date = date.today()

    t = is_flu_season(offer_date)

    facilities  = facilities_df.reset_index(drop=True)
    fac_names   = facilities["ProviderName"].tolist()
    N = len(fac_names)
    P = len(snapshot)

    D             = np.zeros((P, N), dtype=float)
    gender_blocks: list[tuple[int, int]] = []

    # Pre-compute facility-level scalars
    h_n_arr = np.array([funding_to_h_n(facilities.loc[n, "funding"]) for n in range(N)])
    u_n_arr = np.array([u_n_map.get(fac_names[n], 0.0) for n in range(N)])
    gender_lim_arr = [gender_map.get(fac_names[n]) for n in range(N)]

    for p_idx, client in snapshot.iterrows():
        r_p  = client["r_p"]
        q_p  = client["q_p"]
        c_gender = client["ClientGender"]

        for n_idx in range(N):
            g_pn = is_gender_mismatch(c_gender, gender_lim_arr[n_idx])
            h_n  = h_n_arr[n_idx]
            u_n  = u_n_arr[n_idx]

            D[p_idx, n_idx] = compute_p_pn(r_p, q_p, h_n, g_pn, t, u_n)

            if g_pn == 1:
                gender_blocks.append((p_idx, n_idx))

    return D, gender_blocks


# ---------------------------------------------------------------------------
# 5.  Convenience wrapper
# ---------------------------------------------------------------------------

def prepare_model_inputs(
    entries_df: pd.DataFrame,
    facilities_df: pd.DataFrame,
    vacancies_df: pd.DataFrame,
    offer_date: date | None = None,
    verbose: bool = True,
) -> dict:
    """
    Full pipeline: entries + facilities + vacancies → D matrix + metadata.

    Returns
    -------
    dict with keys:
        snapshot       : client DataFrame (P rows)
        facilities     : facility DataFrame (N rows)
        D              : np.ndarray (P, N)
        gender_blocks  : list[(p_idx, n_idx)]
        capacities     : list[int] length N
        u_n_map        : dict {ProviderName: u_n}
        client_ids     : list[int] length P  (PatientID)
        facility_names : list[str] length N  (ProviderName)
    """
    if verbose:
        print("  Building client snapshot...")
    snapshot = build_client_snapshot(entries_df)

    if verbose:
        print("  Recovering facility random effects...")
    u_n_map = recover_facility_effects(entries_df, facilities_df)

    if verbose:
        print("  Computing facility-level gender limitations...")
    gender_map = build_gender_map(vacancies_df)

    if verbose:
        print(f"  Building {len(snapshot)}×{len(facilities_df)} D matrix...")
    D, gender_blocks = build_D_matrix(
        snapshot, facilities_df, u_n_map, gender_map, offer_date
    )

    capacities = facilities_df["Total LTC Beds"].tolist()

    if verbose:
        print(f"  D matrix: mean={D.mean():.4f}, min={D.min():.4f}, max={D.max():.4f}")
        n_blocked = len(gender_blocks)
        print(f"  Gender blocks: {n_blocked} ({n_blocked/(len(snapshot)*len(facilities_df))*100:.1f}% of pairs)")

    return {
        "snapshot":        snapshot,
        "facilities":      facilities_df.reset_index(drop=True),
        "D":               D,
        "gender_blocks":   gender_blocks,
        "capacities":      capacities,
        "u_n_map":         u_n_map,
        "client_ids":      snapshot["PatientID"].tolist(),
        "facility_names":  facilities_df["ProviderName"].tolist(),
    }
